server:
  port: 8080
spring:
  profiles:
    active: dev
---

server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8081
spring:
  profiles: prod

---

#person:
#  name: zhangsan
#  age: 23
#  boss: false
#  birth: 2017/12/12
#  map: {k1: v1,k2: 12,k3: cris}
#  list:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 招财
#    age: 3